### PR TITLE
Sync to upstream 1.3.1

### PR DESCRIPTION
**Pull request by jsburklund**
Update to libpointmatcher 1.3.1

All unit tests provided in libpointmatcher pass, and tested in simulation with Anymal Bany navigation sim for about 5 minutes with no issues.

### CODE REVIEW

**Comment by YoshuaNava** [comment]
This PR looks great!
From the source files I read that we'll now have robust outlier filtering for ICP, new distance filters, error minimizers, smart pointers replaced raw pointers, support for Windows and OpenMP.

Do you observe any difference in performance (accuracy / computational resources)?

**Comment by remod** [comment]
From the commit history, I read that they updated the minimal version of libnabo. I think it makes sense to also update our fork there: https://github.com/ANYbotics/libnabo
It's only 7 commits (and not a lot changed), but for the sake of consistency.

**Comment by jsburklund** [comment]
This currently crashes on the real robot with a segfault somewhere during the setup and initialization, but works fine in simulation. Investigating further before ready to merge.

**Comment by YoshuaNava** [comment]
@jsburklund I think it's really good that you tested this on the robot.

Keep us updated about the results. :)

**Comment by jsburklund** [comment]
Crashes were caused by a mismatch in compiled libraries that pointmatcher_ros used from libpointmatcher. The pointmatcher_ros package required an update to use smart pointers, and needs to be synchronized with this pull request.
https://github.com/ANYbotics/pointmatcher-ros/pull/13

Tested successfully in simulation with anymal_badger_navigation_sim, and on the badger npc. What else needs to be done to validate these updates?

**Comment by YoshuaNava** [comment]
I would say nothing more. Did you observe any difference in performance during your tests? I noticed that they enabled OpenMP.

**Comment by jsburklund** [comment]
> I would say nothing more. Did you observe any difference in performance during your tests? I noticed that they enabled OpenMP.

It looks like they added it to the CMake, but from a quick search through the code, they don't seem to be using it directly in any of the filters.

**Comment by jsburklund** [comment]
> Crashes were caused by a mismatch in compiled libraries that pointmatcher_ros used from libpointmatcher. The pointmatcher_ros package required an update to use smart pointers, and needs to be synchronized with this pull request.
> [ANYbotics/pointmatcher-ros#13](https://github.com/ANYbotics/pointmatcher-ros/pull/13)
> 
> Tested successfully in simulation with anymal_badger_navigation_sim, and on the badger npc. What else needs to be done to validate these updates?

What needs to be done to test the update to libnabo as well? Just test execution on the robot, and in sim?

**Comment by remod** [comment]
Libnabo should undergo the same procedure (PR to sync to upstream), and then you could test the 3 PRs in sim and on the robot.

**Comment by YoshuaNava** [comment]
I would suggest using a tool like [psrecord ](https://github.com/astrofrog/psrecord) to generate a plot of CPU/memory usage. You could attach it to the nodes that use pointmatcher/libnabo for the duration of your tests.

I know this could be too much overhead, but as the size of this PR is significant, that will give us some insight about what to expect in terms of performance.

**Comment by jsburklund** [comment]
Ready to merge. Needs to be synchronized with pointmatcher-ros update PR.

**Review by YoshuaNava — APPROVED** [review]

**Comment by YoshuaNava** [comment]
Thanks! @jsburklund

**Pull request merged**
